name: CI

on: push

jobs:
  ucc-gen:
    name: Generate App Bundle
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade splunk-add-on-ucc-framework==5.5.5
      
      - name: Bundling app
        run: |
          ucc-gen --ta-version 0.0.1
          mkdir dist
          tar -zcvf dist/splunk-app-for-dspt-compliance-v0.0.1.tgz -C output splunk_app_for_dspt_compliance/
      
      - uses: actions/upload-artifact@v2
        with:
          name: app_tgz
          path: dist/splunk-app-for-dspt-compliance-v0.0.1.tgz

      - uses: actions/upload-artifact@v2
        with:
          name: ucc_out
          path: output/splunk_app_for_dspt_compliance

  appinspect-cli:
    name: AppInspect CLI Validation
    needs: ucc-gen
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: ucc_out

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.7"
      
      - name: Install dependencies
        run: |
          sudo apt-get install libxml2-dev libxslt1-dev
          python -m pip install http://download.splunk.com/misc/appinspect/splunk-appinspect-latest.tar.gz
      
      - name: Run AppInspect
        run: |
          ls -la
          ls -la ../
          splunk-appinspect inspect splunk_app_for_dspt_compliance --output-file appinspect.json
          exit `cat appinspect.json | jq '.summary.failure'`
        working-directory: ./output

