name: CI

on: push

jobs:
  ucc-gen:
    name: Generate App Bundle
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      
      - name: Get version
        id: version
        run: |
          VERSION=$(cat package/default/app.conf | grep -e ^version | awk '{print $3}')
          echo "::set-output name=VERSION::$VERSION"
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade splunk-packaging-toolkit splunk-add-on-ucc-framework

      - name: Bundling app
        run: |
          ucc-gen --ta-version ${{ steps.version.outputs.VERSION }}
          cp README.md output/splunk_app_for_dspt_compliance/
          mkdir dist
          slim package output/splunk_app_for_dspt_compliance -o dist/

      - uses: actions/upload-artifact@v2
        with:
          name: app_tgz
          path: dist/splunk_app_for_dspt_compliance-${{ steps.version.outputs.VERSION }}.tar.gz

  appinspect-cli:
    name: AppInspect CLI Validation
    needs: ucc-gen
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: app_tgz

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.7"
      
      - name: Install dependencies
        run: |
          sudo apt-get install libxml2-dev libxslt1-dev
          python -m pip install http://download.splunk.com/misc/appinspect/splunk-appinspect-latest.tar.gz
      
      - name: Run AppInspect
        run: |
          ls -la
          splunk-appinspect inspect splunk_app_for_dspt_compliance-0.0.1.tar.gz --output-file appinspect.json
          exit `cat appinspect.json | jq '.summary.failure'`

